packages:
  - packages/*
  - examples/*

onlyBuiltDependencies:
  - "@swc/core"
  - "@tailwindcss/oxide"
  - esbuild
  - unrs-resolver

overrides:
  "@mcansh/vite-plugin-svg-sprite": "workspace:"
  "@mcansh/vite-svg-sprite-plugin": "workspace:"
